name: Java CI
on:
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: |
           cd gcn
           ./gradlew check --refresh-dependencies --continue
           cd ..
      - name: Verify CLI
        run: |
          cd gcn
          ./gradlew :gcn-cli:assemble
          cp gcn-cli/build/distributions/gcn-cli-*.zip cli.zip
          unzip cli -d tmp
          mv tmp/gcn-cli-* tmp/cli
          ./tmp/cli/bin/gcn --version
